---
title: '`useReverification()`'
description: Clerk's useReverification() hook automatically handles a re-verification flow for you.
---

By wrapping your fetcher with `useReverification()`, we will automatically show a modal the end-user can interact with in order to re-verify their session. Once they successfully complete this step, the hook will attempt the original request one more time.

## `useReverification(fetcher, options)` parameters

| Parameters | Description |
| - | - |
| `fetcher` | `CFetcher extends (…args: any) ⇒ Promise<any>` |
| `options?` | [`UseReverificationOptions`](#use-reverification-options) |

### UseReverificationOptions

| Properties | Description |
| - | - |
| `throwOnCancel?` | `boolean`. Whether or not to throw an error when the reverification flow is cancelled by the user. Defaults to `false`. |
| `onCancel?` | `() ⇒ void`. A callback that will be called if the reverification flow is cancelled by the user. |

## `useReverification(fetcher)` returns

It returns an array with the "enhanced" fetcher.

## How to use the `useReverification()` hook

### Handle user cancelling the flow.

In this example `myData` may be null, since a end-user may close the modal, causing the flow to be cancelled.

```tsx
import { useReverification } from '@clerk/react'

export function MyButton() {
  const [enhancedFetcher] = useReverification(myFetcher)

  return (
    <button
      onClick={async () => {
        const myData = await enhancedFetcher()
        if (!myData) return
        console.log(myData)
      }}
    >
      Update User
    </button>
  )
}
```

### Throw an error when user cancels

In case the end-user closes the modal before re-verifying (cancelling) and you have set `throwOnCancel: true` then your fetcher will throw a `ClerkRuntimeError` with code `reverification_cancelled` . You can use this, to display a toast notification, or simply ignore the error.

```tsx
import { useReverification } from '@clerk/react'

export function MyButton() {
  const [enhancedFetcher] = useReverification(myFetcher, { throwOnCancel: true })

  return (
    <button
      onClick={async () => {
        try {
          const myData = await enhancedFetcher()
          console.log(myData)
        } catch (e) {
          if (isClerkRuntimeError(e) && e.code === 'reverification_cancelled') {
            // The user has cancelled
          }
        }
      }}
    >
      Update User
    </button>
  )
}
```
